from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QRadioButton, QWidget, QPushButton, QLabel, QVBoxLayout, QGroupBox, QHBoxLayout
from random import shuffle
app = QApplication([])
main_win = QWidget()
main_win.setWindowTitle('memory_card')
main_win.resize(2000, 1000)
title = QLabel('Какой национальности не существует?')
v_line = QVBoxLayout()
v_line.addWidget(title, alignment = Qt.AlignCenter)
main_win.setLayout(v_line)
btn_answer1 = QRadioButton('Энцы')
btn_answer2 = QRadioButton('Чулымцы')
btn_answer3 = QRadioButton('Смурфы')
btn_answer4 = QRadioButton('Алеуты')
v_line.addWidget(btn_answer1, alignment = Qt.AlignCenter)
v_line.addWidget(btn_answer2, alignment = Qt.AlignCenter)
v_line.addWidget(btn_answer3, alignment = Qt.AlignCenter)
v_line.addWidget(btn_answer4, alignment = Qt.AlignCenter)
radiogroupbox = QGroupBox('Энцы')
layout_quest = QVBoxLayout()
layout_quest.addWidget(btn_answer1)
layout_quest.addWidget(btn_answer2)
layout_quest1 = QVBoxLayout()
layout_quest1.addWidget(btn_answer3)
layout_quest1.addWidget(btn_answer4)
layout_quest2 = QHBoxLayout()
layout_quest2.addLayout(layout_quest)
layout_quest2.addLayout(layout_quest1)
radiogroupbox.setLayout(layout_quest2)
layout_quest.setSpacing(5)

main_win.show()
app.exec_()